models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ~/cs4501/app:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --reload-on-changes --working-directory /app/stockexchange /app/stockexchange/stockapp/wsgi.py"