models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  volumes:
    - ./models-api:/app
  ports:
    - "8001:8000"
  command: bash -c "python stockexchange/manage.py makemigrations && python stock-exchange/manage.py migrate && python stockexchange/manage.py loaddata stockexchange/db.json && mod_wsgi-express start-server --working-directory /app/stockexchange --reload-on-changes /app/stockexchange/stockexchange/wsgi.py"

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
  volumes:
    - ./exp-api:/app
  ports:
    - "8002:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory /app/exp --reload-on-changes /app/exp/exp/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  volumes:
    - ./web-layer:/app
  ports:
    - "8000:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory /app/web --reload-on-changes /app/web/web/wsgi.py"

# kafka:
#    image: spotify/kafka
#    container_name: kafka
#    environment:
#       ADVERTISED_HOST: kafka
#       ADVERTISED_PORT: 9092
#    hostname: kafka
   
# es:
#    image: elasticsearch:2.0
#    container_name: es
#    ports:
#       - "9200:9200"

# batch:
#    image: tp33/django
#    container_name: batch
#    volumes:
#     - ./batch:/app
#    links:
#       - kafka:kafka
#       - es:es
#     command: <run a python script that pulls messages from Kafka and indexs that in ES>