# Generated by Django 2.1 on 2019-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=30)),
                ('authenticator', models.CharField(max_length=70)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
