# Generated by Django 2.1 on 2019-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='item',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_items',
            field=models.CharField(max_length=50),
        ),
    ]
